export const ANOMALY_TYPE_CODES = {
  ABSENCE_LISTE_COLISAGE: 'ABSENCE_LISTE_COLISAGE',
  ORDRE_MAGASIN_NON_CONFORME: 'ORDRE_MAGASIN_NON_CONFORME',
  DONNEE_MANQUANTE: 'DONNEE_MANQUANTE',
  DUPLICATION_PRESTATION: 'DUPLICATION_PRESTATION',
} as const;
